version: "3"

services: 
    app:
        build: 
            context: .
        ports: 
            - "8000:8000" # Map port 8000 of host machine to 8000 of docker engine
        volumes: 
            - ./app:/app  
        command: > 
            sh -c "python manage.py runserver 0.0.0.0:8000"